#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt',
  git: 'https://github.com/fnichol/chef-apt'

cookbook 'git',
  git: 'https://github.com/fnichol/chef-git.git'

cookbook 'rvm',
  git: 'https://github.com/fnichol/chef-rvm'

cookbook 'build-essential'
cookbook 'openssl'
cookbook 'mysql'
cookbook 'rabbitmq'
cookbook 'nginx'
